name: ServerStatus
main: me.BestInTest.ServerStatus.Main
author: BestInTest
version: 1.2
commands:
  status:
    description: Pokazuje status sesji serwera
  atps:
    description: Pokazuje statystyki tpsu serwera
  diskcheck:
    description: Sprawdzanie miejsca na dysku